src/objects/Comment__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>コメント</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Guest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ゲスト</label>
        <referenceTo>Guest__c</referenceTo>
        <relationshipLabel>コメント</relationshipLabel>
        <relationshipName>Comment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>セッション</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>コメント</relationshipLabel>
        <relationshipName>Comment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>コメント</label>
    <nameField>
        <displayFormat>CMT-{00000000}</displayFormat>
        <label>コメント番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Custom_Survey_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Guest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ゲスト</label>
        <referenceTo>Guest__c</referenceTo>
        <relationshipLabel>カスタムアンケート 回答</relationshipLabel>
        <relationshipName>Custom_Survey_Answer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>セッション</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>カスタムアンケート 回答</relationshipLabel>
        <relationshipName>Custom_Survey_Answer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>カスタムアンケート 回答</label>
    <nameField>
        <displayFormat>CSA-{00000000}</displayFormat>
        <label>回答番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Guest__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>名</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>イベント</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>ゲスト</relationshipLabel>
        <relationshipName>Guest</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ゲスト</label>
    <nameField>
        <displayFormat>GST-{00000000}</displayFormat>
        <label>ゲスト番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <label>すごいアンケート</label>
    <nameField>
        <label>アンケートタイトル</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Guest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ゲスト</label>
        <referenceTo>Guest__c</referenceTo>
        <relationshipLabel>アンケート</relationshipLabel>
        <relationshipName>Survey</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>セッション</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>アンケート</relationshipLabel>
        <relationshipName>Survey</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>アンケート</label>
    <nameField>
        <displayFormat>SVY-{00000000}</displayFormat>
        <label>アンケート番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/validate_guest_cascade_delete.cls
@isTest
private class validate_guest_cascade_delete {
    static testmethod void validate_guest_cascade_delete(){
        session__c session = validate_session.createDummySession('poiqjefpoerfj', system.label.picklist_require_email, system.label.picklist_require_survey_submission);
        guest__c g = [select id from guest__c where session__c = :session.id and first_name__c = 'uruffjjfr'];
        jr_session.copy_comment_to_feedItem(session.id);
        list<feedItem> feedItems = [select id, linkUrl from feedItem where parentId = :session.id];
        string linkUrl = '/' + g.id;
        system.assertEquals(1, [select id from survey__c where guest__c = :g.id].size());
        system.assertEquals(2, [select id from custom_survey_answer__c where guest__c = :g.id].size());
        system.assertEquals(1, [select id from comment__c where guest__c = :g.id].size());
        
        list<feedItem> feedItems_to_del = new list<feedItem>();
        for (feedItem fi : feedItems){
            if (fi.linkUrl == linkUrl){
                feedItems_to_del.add(fi);
            }
        }
        system.assertEquals(1, feedItems_to_del.size());
        
        delete g;
        system.assertEquals(0, [select id from survey__c where guest__c = :g.id].size());
        system.assertEquals(0, [select id from custom_survey_answer__c where guest__c = :g.id].size());
        system.assertEquals(0, [select id from comment__c where guest__c = :g.id].size());
        feedItems.clear();
        feedItems = [select id, linkUrl from feedItem where parentId = :session.id];
        feedItems_to_del.clear();
        for (feedItem fi : feedItems){
            if (fi.linkUrl == linkUrl){
                feedItems_to_del.add(fi);
            }
        }
        system.assertEquals(0, feedItems_to_del.size());
    }
}