src/objects/Comment__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>コメント</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Guest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ゲスト</label>
        <referenceTo>Guest__c</referenceTo>
        <relationshipLabel>コメント</relationshipLabel>
        <relationshipName>Comment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>セッション</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>コメント</relationshipLabel>
        <relationshipName>Comment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>コメント</label>
    <nameField>
        <displayFormat>CMT-{00000000}</displayFormat>
        <label>コメント番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Custom_Survey_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Custom_Survey_Option__c</fullName>
        <label>選択肢</label>
        <referenceTo>Custom_Survey_Option__c</referenceTo>
        <relationshipLabel>カスタムアンケート 回答</relationshipLabel>
        <relationshipName>Custom_Survey_Answer</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Guest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ゲスト</label>
        <referenceTo>Guest__c</referenceTo>
        <relationshipLabel>カスタムアンケート 回答</relationshipLabel>
        <relationshipName>Custom_Survey_Answer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>セッション</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>カスタムアンケート 回答</relationshipLabel>
        <relationshipName>Custom_Survey_Answer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>カスタムアンケート 回答</label>
    <nameField>
        <displayFormat>CSA-{00000000}</displayFormat>
        <label>回答番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Custom_Survey_Option__c.object
<CustomObject>
    <fields>
        <fullName>Custom_Survey_Question__c</fullName>
        <label>質問</label>
        <referenceTo>Custom_Survey_Question__c</referenceTo>
        <relationshipLabel>カスタムアンケート 選択肢</relationshipLabel>
        <relationshipName>Custom_Survey_Option</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Dummy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ダミー</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Free_Form__c</fullName>
        <defaultValue>false</defaultValue>
        <label>自由回答欄</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Option__c</fullName>
        <label>選択肢</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>セッション</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>カスタムアンケート 選択肢</relationshipLabel>
        <relationshipName>Custom_Survey_Option</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>カスタムアンケート 選択肢</label>
    <nameField>
        <displayFormat>CSO-{00000000}</displayFormat>
        <label>選択肢番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Custom_Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Enable_Free_Form__c</fullName>
        <defaultValue>false</defaultValue>
        <label>自由回答欄</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>質問</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>回答必須</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>セッション</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>カスタムアンケート 質問</relationshipLabel>
        <relationshipName>Custom_Survey_Question</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_Type__c</fullName>
        <label>アンケートタイプ</label>
        <picklist>
            <picklistValues>
                <fullName>checkbox</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>free</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>カスタムアンケート 質問</label>
    <nameField>
        <displayFormat>CSQ-{00000000}</displayFormat>
        <label>質問番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Guest__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>会社</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>名</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>姓</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>イベント</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>ゲスト</relationshipLabel>
        <relationshipName>Guest</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>状況</label>
        <picklist>
            <picklistValues>
                <fullName>registered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>submitted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>役職</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ゲスト</label>
    <nameField>
        <displayFormat>GST-{00000000}</displayFormat>
        <label>ゲスト番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>開催日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Handout_Password__c</fullName>
        <label>資料開封パスワード</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handout_URL__c</fullName>
        <label>資料ダウンロードURL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Mass_Mail_Additional_Body__c</fullName>
        <label>メール本文(HTML)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Mass_Mail_Sender__c</fullName>
        <label>メール送信元アドレス</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Post_To_Account_Record_Feed__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>チェックすると、ゲストが登録された時またはアンケートを回答した時に、そのゲストに該当する取引先レコードがあれば、そのレコードフィードに活動が投稿されます。</inlineHelpText>
        <label>取引先のレコードフィードにゲストの活動を投稿</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Post_To_Contact_Record_Feed__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>チェックすると、ゲストが登録された時またはアンケートを回答した時に、そのゲストに該当する取引先責任者レコードがあれば、そのレコードフィードに活動が投稿されます。</inlineHelpText>
        <label>取引先責任者のレコードフィードにゲストの活動を投稿</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Who_Can_Get_Handout__c</fullName>
        <label>メールを配信される人</label>
        <picklist>
            <picklistValues>
                <fullName>全員</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>出席者</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>アンケートの入力が必要</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Who_Can_Submit_Survey__c</fullName>
        <label>アンケートを入力できる人</label>
        <picklist>
            <picklistValues>
                <fullName>無条件</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eメールの入力が必要</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>事前登録者のみ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>すごいアンケート</label>
    <nameField>
        <label>アンケートタイトル</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Guest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ゲスト</label>
        <referenceTo>Guest__c</referenceTo>
        <relationshipLabel>アンケート</relationshipLabel>
        <relationshipName>Survey</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>評価</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>セッション</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>アンケート</relationshipLabel>
        <relationshipName>Survey</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>アンケート</label>
    <nameField>
        <displayFormat>SVY-{00000000}</displayFormat>
        <label>アンケート番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/validate_session.cls
@isTest
public class validate_session {
    public static Session__c createDummySession(String session_name, String who_can_submit_survey, String who_can_get_handout) {
        Session__c session = new Session__c(
            name = session_name,
            date__c = date.valueOf('2012-09-30'),
            who_can_submit_survey__c = who_can_submit_survey,
            who_can_get_handout__c = who_can_get_handout,
            mass_mail_sender__c = 'test@hoge.com',
            handout_url__c = 'http://hoge.com',
            Post_To_Account_Record_Feed__c = false,
            Post_To_Contact_Record_Feed__c = false
        );
        insert session;
        
        //create dummy handout
        Attachment attachment1 = new Attachment(parentid=session.id, name='test attachment1', contenttype='text/plain', body=blob.valueOf('test body1'));
        Attachment attachment2 = new Attachment(parentid=session.id, name='test attachment2', contenttype='text/plain', body=blob.valueOf('test body2'));
        insert attachment1;
        insert attachment2;
        
        //create dummy guest
        guest__c guest1 = new guest__c(status__c = 'submitted', session__c=session.id, last_name__c='test guest1', email__c='hoge1@hoge.com', first_name__c='uruffjjfr', title__c='rufhbrfjjf', company__c='jfjieerjfkf');
        guest__c guest2 = new guest__c(status__c = 'submitted', session__c=session.id, last_name__c='test guest2', email__c='hoge2@hoge.com');
        guest__c guest3 = new guest__c(status__c = 'submitted', session__c=session.id, last_name__c='test guest3', email__c='hoge3@hoge.com');
        guest__c guest4 = new guest__c(status__c = 'submitted', session__c=session.id, last_name__c='test guest4', email__c='hoge4@hoge.com');
        guest__c guest5 = new guest__c(status__c = 'submitted', session__c=session.id, last_name__c='test guest5', email__c='hoge5@hoge.com');
        guest__c guest6 = new guest__c(session__c=session.id, last_name__c='test guest6', email__c='hoge6@hoge.com');
        insert guest1;
        insert guest2;
        insert guest3;
        insert guest4;
        insert guest5;
        insert guest6;
        
        //create dummy question
        custom_survey_question__c csq1 = new custom_survey_question__c(session__c=session.id, question__c='test question1');
        insert csq1;
        
        //create dummy option
        custom_survey_option__c cso1 = new custom_survey_option__c(session__c=session.id, custom_survey_question__c=csq1.id, option__c='test option1');
        custom_survey_option__c cso2 = new custom_survey_option__c(session__c=session.id, custom_survey_question__c=csq1.id, option__c='test option2');
        insert cso1;
        insert cso2;
        
        //create dummy survey
        survey__c survey1 = new survey__c(session__c=session.id, guest__c=guest1.id, rate__c=1);
        survey__c survey2 = new survey__c(session__c=session.id, guest__c=guest2.id, rate__c=2);
        survey__c survey3 = new survey__c(session__c=session.id, guest__c=guest3.id, rate__c=3);
        survey__c survey4 = new survey__c(session__c=session.id, guest__c=guest4.id, rate__c=4);
        survey__c survey5 = new survey__c(session__c=session.id, guest__c=guest5.id, rate__c=5);
        insert survey1;
        insert survey2;
        insert survey3;
        insert survey4;
        insert survey5;
        
        //create dummy comment
        comment__c comment1 = new comment__c(session__c=session.id, guest__c=guest1.id, comment__c='test comment1');
        comment__c comment2 = new comment__c(session__c=session.id, guest__c=guest2.id, comment__c='test comment2');
        insert comment1;
        insert comment2;
        
        //create dummy tweet
        /*
        tweet__c tweet1 = new tweet__c(session__c=session.id, id__c='00000000', text__c='test text 1');
        tweet__c tweet2 = new tweet__c(session__c=session.id, id__c='00000001', text__c='text text 2');
        insert tweet1;
        insert tweet2;
        */
        
        //create dummy answer
        custom_survey_answer__c csa1 = new custom_survey_answer__c(session__c=session.id, guest__c=guest1.id, custom_survey_option__c=cso1.id);
        custom_survey_answer__c csa2 = new custom_survey_answer__c(session__c=session.id, guest__c=guest1.id, custom_survey_option__c=cso2.id);
        custom_survey_answer__c csa3 = new custom_survey_answer__c(session__c=session.id, guest__c=guest2.id, custom_survey_option__c=cso1.id);
        insert csa1;
        insert csa2;
        insert csa3;
        
        return session;
    }
    
    public static Session__c createDummySessionIncludeRequiredQuestion() {
        Session__c session = new Session__c(
            name = '9ejlflkldsflkjdf'
        );
        insert session;
        
        //create dummy question
        custom_survey_question__c csq1 = new custom_survey_question__c(session__c=session.id, question__c='q1_h9hefljlkjf', survey_type__c = 'checkbox', required__c=false);
        custom_survey_question__c csq2 = new custom_survey_question__c(session__c=session.id, question__c='q2_oiuj0wfjoie', survey_type__c = 'radio', required__c=true);
        custom_survey_question__c csq3 = new custom_survey_question__c(session__c=session.id, question__c='q3_dfjf0wfsdfj', survey_type__c = 'free', required__c=false);
        insert csq1;
        insert csq2;
        insert csq3;
        
        //create dummy option
        custom_survey_option__c cso1 = new custom_survey_option__c(session__c=session.id, custom_survey_question__c=csq1.id, option__c='o1_ldjfojwef');
        custom_survey_option__c cso2 = new custom_survey_option__c(session__c=session.id, custom_survey_question__c=csq1.id, option__c='o2_ljsdkflkj');
        insert cso1;
        insert cso2;
        custom_survey_option__c cso3 = new custom_survey_option__c(session__c=session.id, custom_survey_question__c=csq2.id, option__c='o1_3rfjpofb');
        custom_survey_option__c cso4 = new custom_survey_option__c(session__c=session.id, custom_survey_question__c=csq2.id, option__c='o2_djfhonfk');
        insert cso3;
        insert cso4;
        custom_survey_option__c cso5 = new custom_survey_option__c(session__c=session.id, custom_survey_question__c=csq3.id, option__c='o1_0ifoflkdf', dummy__c = true, enable_free_form__c = true);
        insert cso5;

        return [
        	select 
        		id, name,
        		(select id, name, question__c from custom_survey_question__r),
        		(select id, name, option__c from custom_survey_option__r)
    		from session__c
    		where id = :session.id
		];
    }
    
    static testmethod void validate_getSession(){
    	Session__c session1 = createDummySession('test session1', system.label.picklist_require_email, system.label.picklist_require_survey_submission);
    	ApexPages.StandardController sc1 = new ApexPages.StandardController(session1);
        session_v2 sugoi_session1 = new session_v2(sc1);
        system.assertEquals('test session1', sugoi_session1.getSession().name);
    }
    
    static testmethod void validate_getSessions(){
    	Session__c session1 = createDummySession('test session1', system.label.picklist_require_email, system.label.picklist_require_survey_submission);
    	ApexPages.StandardController sc1 = new ApexPages.StandardController(session1);
        session_v2 sugoi_session1 = new session_v2(sc1);
        system.assertEquals(1, sugoi_session1.getSessions().size());
        system.assertEquals('test session1', sugoi_session1.getSessions()[0].name);
    }
    
    static testmethod void validate_getDeliveryDestinations(){
     	session__c session;
    	ApexPages.StandardController sc;
    	session_v2 i_session;
    	PageReference pr;
    	list<guest__c> guests;
    	
    	session = createDummySession('test session', system.label.picklist_require_email, system.label.picklist_require_survey_submission);
        sc = new ApexPages.StandardController(session);
        i_session = new session_v2(sc);
        guests = i_session.getDeliveryDestinations();
        system.assertEquals(5, guests.size());
        
        session = createDummySession('test session', system.label.picklist_require_email, system.label.picklist_anyone);
        sc = new ApexPages.StandardController(session);
        i_session = new session_v2(sc);
        guests = i_session.getDeliveryDestinations();
        system.assertEquals(6, guests.size());
    }
    
    static testmethod void validate_getMailBody(){
    	session__c session;
    	ApexPages.StandardController sc;
    	session_v2 i_session;
    	PageReference pr;
    	
    	session = createDummySession('jfuvdedikfkvmd', system.label.picklist_require_email, system.label.picklist_require_survey_submission);
        session.mass_mail_additional_body__c = 'ksldhfoihoedfjosdklf';
        session.handout_url__c = 'https://woieur.woeifjoeiwjfow.com';
        session.handout_password__c = 'kriigjeifnief';
        update session;
        
        sc = new ApexPages.StandardController(session);
        i_session = new session_v2(sc);
        
        string mail_body = i_session.getMailBody();
        system.assertEquals('<p>ksldhfoihoedfjosdklf</p><p>' + system.label.handout_download_url + ' : <a href="https://woieur.woeifjoeiwjfow.com">https://woieur.woeifjoeiwjfow.com</a><br/>' + system.label.password + ' : kriigjeifnief</p>', mail_body);
    }
}