src/objects/config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>initialized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>初期化</label>
        <type>Checkbox</type>
    </fields>
    <label>すごいアンケート設定</label>
</CustomObject>

src/objects/Guest__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>会社</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Handout_Delivered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>資料配信済み</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>IF(ISBLANK(First_Name__c), 
Last_Name__c,
Last_Name__c + &apos; &apos; +  First_Name__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>名前</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>イベント</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>ゲスト</relationshipLabel>
        <relationshipName>Guest</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>役職</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ゲスト</label>
    <nameField>
        <displayFormat>GST-{00000000}</displayFormat>
        <label>ゲスト番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Presenter__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>会社</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>役職</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>プレゼンター</label>
    <nameField>
        <label>プレゼンター名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>開催日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Handout_Password__c</fullName>
        <label>資料開封パスワード</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handout_URL__c</fullName>
        <label>資料ダウンロードURL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Mass_Mail_Additional_Body__c</fullName>
        <label>メール本文(HTML)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Open__c</fullName>
        <defaultValue>true</defaultValue>
        <label>オープン</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Presenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>プレゼンター</label>
        <referenceTo>Presenter__c</referenceTo>
        <relationshipName>Session</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Avg__c</fullName>
        <formula>IF ( Rate_Count__c  &lt;&gt; 0 &amp;&amp; Rate_Sum__c &lt;&gt; 0, ROUND(Rate_Sum__c / Rate_Count__c, 2), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>評価平均</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Who_Can_Get_Handout__c</fullName>
        <label>メールを配信される人</label>
        <picklist>
            <picklistValues>
                <fullName>全員</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>出席者</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>アンケートの入力が必要</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>すごいアンケート</label>
    <nameField>
        <label>アンケートタイトル</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Guest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ゲスト</label>
        <referenceTo>Guest__c</referenceTo>
        <relationshipLabel>アンケート</relationshipLabel>
        <relationshipName>Survey</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>セッション</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>アンケート</relationshipLabel>
        <relationshipName>Survey</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>アンケート</label>
    <nameField>
        <displayFormat>SVY-{00000000}</displayFormat>
        <label>アンケート番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/session_v2.cls
public with sharing class session_v2 {
    private session__c session;
 
    public session_v2(ApexPages.StandardController controller) {
        session__c session = (session__c)controller.getRecord();
        if (session.id != null) {
        	this.session = jr_session.get_session(session.id);
        }
    }

    public class sugoiSurveyResult {
        public boolean status {get; set;}
        public string message {get; set;}
        public id record_id {get; set;}
    }

    public session__c getSession(){
        return this.session;
    }

    public list<session__c> getSessions(){
        return [
            select 
                id,
                name,
                date__c,
                rate_avg__c,
                open__c,
                presenter__r.name,
                presenter__r.title__c,
                presenter__r.company__c
            from session__c order by date__c desc, createdDate desc
        ];
    }
    
    public static config__c config = config__c.getOrgDefaults();

    // Get method for retrieving custom setting
    public static config__c getConfig(){
        return config;
    }
    
    private static testmethod void validate_getConfig(){
        config.initialized__c = true;
        upsert config;
        system.assertEquals(true, getConfig().initialized__c);
    }
    
    public list<guest__c> getDeliveryDestinations(){
        list<guest__c> deliveryDestinations = new list<guest__c>();
        if (this.session.who_can_get_handout__c == '全員' || this.session.who_can_get_handout__c == 'Everyone'){
            for (Guest__c guest : this.session.guest__r){
                if (guest.email__c != '' && guest.email__c != null){
					deliveryDestinations.add(guest);
                }
            }
        } else if (this.session.who_can_get_handout__c == 'アンケートの入力が必要' || this.session.who_can_get_handout__c == 'Survey Required'){
            List<id> guest_ids_submitted_survey = new List<id>();
            for (Survey__c survey : this.session.survey__r){
                guest_ids_submitted_survey.add(survey.guest__c);
            }
            if (guest_ids_submitted_survey.size() >= 1){
                try {
                	deliveryDestinations = [select name__c, email__c, company__c, title__c, handout_delivered__c from guest__c where id in :guest_ids_submitted_survey and email__c != '' order by handout_delivered__c, company__c];
                } catch (Exception e){
                }
            }
        }
        return deliveryDestinations;
    }
    
    public string getMailBody(){
    	string body = '';
    	if (this.session.mass_mail_additional_body__c != null){
    		body += '<p>' + this.session.mass_mail_additional_body__c + '</p>';
    	}
    	if (this.session.handout_url__c != null){
    		body += '<p>';
    		body += system.label.handout_download_url + ' : <a href="' + this.session.handout_url__c + '">' + this.session.handout_url__c + '</a>';
    		if (this.session.handout_password__c != null){
    			body += '<br/>' + system.label.password + ' : ' + this.session.handout_password__c;
    		}
    		body += '</p>';
    	}
    	return body;
    }
}