src/objects/config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>cron_trigger_id__c</fullName>
        <label>スケジュール済みジョブID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>survey_sites_domain__c</fullName>
        <label>アンケートサイトドメイン</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>すごいアンケート設定</label>
</CustomObject>

src/objects/Guest__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>イベント</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>ゲスト</relationshipLabel>
        <relationshipName>Guest</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>To_Be_Posted_To_Record_Feed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Chatterに投稿する必要有り</label>
        <type>Checkbox</type>
    </fields>
    <label>ゲスト</label>
    <nameField>
        <displayFormat>GST-{00000000}</displayFormat>
        <label>ゲスト番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <label>すごいアンケート</label>
    <nameField>
        <label>アンケートタイトル</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/cron_trigger.cls
global class cron_trigger implements Schedulable{
    global integer interval = 1;
    
    global void execute(SchedulableContext SC) {
        // notify guest registration
        chatter_notification.notify_registration_to_record_feed_for_pending_guest();

        // schedule next copy
        Datetime next = Datetime.now().addMinutes(this.interval);
        string sch = string.valueOf(next.second()) + ' ' + string.valueOf(next.minute()) + ' ' + string.valueOf(next.hour()) + ' ' + string.valueOf(next.day()) + ' ' + string.valueOf(next.month()) + ' ?';
        id cron_trigger_id = System.schedule('Cron Trigger v1.13 - ' + sch, sch, new cron_trigger());

        // update config
        config__c config = config__c.getOrgDefaults();
        config.cron_trigger_id__c = cron_trigger_id;
        upsert config;
        
        // abort this job
        if (!Test.isRunningTest()){
            System.abortJob(sc.getTriggerId());
        }
    }
    
    private static testmethod void validate_execute(){
        list<session__c> sessions = validate_link_to_contact.create_sessions();
        validate_link_to_contact.create_account_and_contacts();
        guest__c g;
        list<feedItem> feedItems;
        
        config__c config = new config__c(survey_sites_domain__c = 'sugoisurvey4-developer-edition.na11.force.com');
        upsert config;
        
        User u = [select id from User where username = 'sugoisurvey@sugoisurvey4-developer-edition.na11.force.com'];
        System.runAs(u){
            g = new guest__c();
            g.email__c = 'aoeifioj@hoge.com';
            g.session__c = sessions[0].id;
            insert g;
        }
        
        list<guest__c> guests = [select to_be_posted_to_record_feed__c from guest__c where session__c = :sessions[0].id];
        system.assertEquals(1, guests.size());
        system.assertEquals(true, guests[0].to_be_posted_to_record_feed__c);
        
        string sch = '0 0 * * * ?';
        Test.startTest();
        System.schedule('Cron Trigger for Validate', sch, new cron_trigger());
        Test.stopTest();

        guests = [select to_be_posted_to_record_feed__c from guest__c where session__c = :sessions[0].id];
        system.assertEquals(false, guests[0].to_be_posted_to_record_feed__c);
    }
}