src/objects/config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>cron_trigger_id__c</fullName>
        <label>スケジュール済みジョブID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>need_re_initialization__c</fullName>
        <defaultValue>false</defaultValue>
        <label>再初期化が必要</label>
        <type>Checkbox</type>
    </fields>
    <label>すごいアンケート設定</label>
</CustomObject>

src/classes/post_install.cls
global class post_install implements InstallHandler {
    global void onInstall(InstallContext context) {
        config__c config = config__c.getOrgDefaults();
        // script for upgrade
        if (context.isUpgrade()){
            if (config.cron_trigger_id__c != null && !Test.isRunningTest()){
                system.abortJob(config.cron_trigger_id__c);
            }
            config.need_re_initialization__c = true;
            upsert config;
        }
    }
    
    @isTest
    static void validate_post_install() {
        config__c config = config__c.getOrgDefaults();
        system.assertEquals(false, config.need_re_initialization__c);
        
        post_install pi = new post_install();
        Test.testInstall(pi, new version(1,0),true);
        
        config = config__c.getOrgDefaults();
        system.assertEquals(true, config.need_re_initialization__c);
    }
}