src/objects/Custom_Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Session__c</fullName>
        <label>セッション</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>カスタムアンケート 質問</relationshipLabel>
        <relationshipName>Custom_Survey_Question</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>カスタムアンケート 質問</label>
    <nameField>
        <displayFormat>CSQ-{00000000}</displayFormat>
        <label>質問番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Guest__c.object
<CustomObject>
    <fields>
        <fullName>Session__c</fullName>
        <label>イベント</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>ゲスト</relationshipLabel>
        <relationshipName>Guest</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ゲスト</label>
    <nameField>
        <displayFormat>GST-{00000000}</displayFormat>
        <label>ゲスト番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <label>すごいアンケート</label>
    <nameField>
        <label>アンケートタイトル</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/guest.cls
public with sharing class guest {
    public guest__c guest {get;set;}

    public guest(ApexPages.StandardController controller) {
        guest__c guest_tmp = (guest__c)controller.getRecord();
        if (guest_tmp.id != null){
            this.guest = (guest__c)scrud.sread('sugoisurvey4__Guest__c', guest_tmp.id);
        }
    }

    public static string getLanguage_locale_key(){
        return [select languageLocaleKey from user where id = :Userinfo.getUserId()].languageLocaleKey;
    }

    public list<custom_survey_question__c> getCustom_Survey_Questions(){
        string soql_flds = scrud.getAccessibleFieldsInCSV('sugoisurvey4__Custom_Survey_Question__c');
        id session_id = this.guest.session__c;
        string soql = 'select ' + soql_flds + ' from custom_survey_question__c where session__c = :session_id order by name';

        list<custom_survey_question__c> csqs = Database.query(soql);
        return csqs;
    }

}