src/objects/Custom_Survey_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>セッション</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>カスタムアンケート 回答</relationshipLabel>
        <relationshipName>Custom_Survey_Answer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>カスタムアンケート 回答</label>
    <nameField>
        <displayFormat>CSA-{00000000}</displayFormat>
        <label>回答番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <label>すごいアンケート</label>
    <nameField>
        <label>アンケートタイトル</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/session_report.cls
public with sharing class session_report {
    public id c_session_id {get;set;}
    public id c_csq_id {get;set;}
    
    /*
    public session__c getSession() {
        return jr_session.get_session(this.c_session_id);
    }

    public String getSession_json() {
        return JSON.serialize(jr_session.get_session(this.c_session_id));
    }
    */
    
    public list<custom_survey_answer__c> getFree_answers(){
        return jr_session.get_free_answers(c_csq_id);
    }
}