src/objects/Custom_Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Session__c</fullName>
        <label>セッション</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>カスタムアンケート 質問</relationshipLabel>
        <relationshipName>Custom_Survey_Question</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>カスタムアンケート 質問</label>
    <nameField>
        <displayFormat>CSQ-{00000000}</displayFormat>
        <label>質問番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Guest__c.object
<CustomObject>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>姓</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>イベント</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>ゲスト</relationshipLabel>
        <relationshipName>Guest</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ゲスト</label>
    <nameField>
        <displayFormat>GST-{00000000}</displayFormat>
        <label>ゲスト番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <label>すごいアンケート</label>
    <nameField>
        <label>アンケートタイトル</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/validate_guest.cls
@isTest
public with sharing class validate_guest {
    private static testMethod void validate_getLanguage_locale_key(){
        system.assertEquals([select languageLocaleKey from user where id = :Userinfo.getUserId()].languageLocaleKey, guest.getLanguage_locale_key());
    }
    
    /*
    private static testMethod void validate_getGuest(){
        session__c session = validate_session.createDummySession('test session1', system.label.picklist_require_email, system.label.picklist_require_survey_submission);
        guest__c guest = new guest__c(last_name__c = 'Nakajima for validate', session__c = session.id);
        insert guest;
        ApexPages.StandardController sc = new ApexPages.StandardController(guest);
        guest sfg = new guest(sc);
        
        guest__c g = sfg.getGuest();
        system.assertEquals(session.id, g.session__c);
    }
    */
    
    private static testmethod void validate_getCustom_Survey_Questions(){
        session__c session = validate_session.createDummySession('test session1', system.label.picklist_require_email, system.label.picklist_require_survey_submission);
        guest__c guest = new guest__c(last_name__c = 'Nakajima for validate', session__c = session.id);
        insert guest;
        ApexPages.StandardController sc = new ApexPages.StandardController(guest);
        guest sfg = new guest(sc);
        
        list<custom_survey_question__c> csqs = sfg.getCustom_Survey_Questions();
        system.assertEquals(1, csqs.size());
    }
}