src/objects/Guest__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>取引先責任者</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ゲスト</relationshipLabel>
        <relationshipName>Guest</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>名</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>IF(ISBLANK(First_Name__c), 
Last_Name__c,
Last_Name__c + &apos; &apos; +  First_Name__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>名前</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>イベント</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>ゲスト</relationshipLabel>
        <relationshipName>Guest</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ゲスト</label>
    <nameField>
        <displayFormat>GST-{00000000}</displayFormat>
        <label>ゲスト番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Post_To_Account_Record_Feed__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>チェックすると、ゲストが登録された時またはアンケートを回答した時に、そのゲストに該当する取引先レコードがあれば、そのレコードフィードに活動が投稿されます。</inlineHelpText>
        <label>取引先のレコードフィードにゲストの活動を投稿</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Post_To_Contact_Record_Feed__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>チェックすると、ゲストが登録された時またはアンケートを回答した時に、そのゲストに該当する取引先責任者レコードがあれば、そのレコードフィードに活動が投稿されます。</inlineHelpText>
        <label>取引先責任者のレコードフィードにゲストの活動を投稿</label>
        <type>Checkbox</type>
    </fields>
    <label>すごいアンケート</label>
    <nameField>
        <label>アンケートタイトル</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/validate_chatter_notification.cls
@isTest
public class validate_chatter_notification {
    private static testmethod void validate_notify_checkin_to_record_feed(){
        boolean r;
        session__c s = validate_session.createDummySession('oiwjefoef', system.label.picklist_require_email, system.label.picklist_require_survey_submission);
        
        /*
        guest is null
         */
        r = chatter_notification.notify_checkin_to_record_feed(null);
        system.assertEquals(false, r);
        
        /*
        guest is set.
        contact is not linked.
         */
        guest__c g = [select id, name__c, session__c, contact__c from guest__c where session__c = :s.id and first_name__c = 'uruffjjfr'];
        r = chatter_notification.notify_checkin_to_record_feed(g);
        system.assertEquals(true, r);
        list<feedItem> fis = [select id, linkUrl from feedItem where parentId = :s.id];
        boolean found = false;
        for (feedItem fi : fis){
            if (fi.linkUrl == '/' + g.id){
                found = true;
                break;
            }
        }
        system.assertEquals(true, found);
        
        /*
        guest is set.
        contact is linked.
        contact exists.
        Post_To_Account_Record_Feed__c is false
        Post_To_Contact_Record_Feed__c is false
         */
        account a = new account(name = 'lksjdfojwedflj');
        insert a;
        contact c = new contact(lastname = 'oidfklwlfeljflk', accountId = a.id);
        insert c;
        g.contact__c = c.id;
        update c;
        
        r = chatter_notification.notify_checkin_to_record_feed(g);
        system.assertEquals(true, r);
        
        fis = [select id, linkUrl from feedItem where parentId = :a.id];
        found = false;
        for (feedItem fi : fis){
            if (fi.linkUrl == '/' + s.id){
                found = true;
                break;
            }
        }
        system.assertEquals(false, found);
        
        fis = [select id, linkUrl from feedItem where parentId = :c.id];
        found = false;
        for (feedItem fi : fis){
            if (fi.linkUrl == '/' + s.id){
                found = true;
                break;
            }
        }
        system.assertEquals(false, found);
        
        /*
        guest is set.
        contact is linked.
        contact exists.
        Post_To_Account_Record_Feed__c is true
        Post_To_Contact_Record_Feed__c is true
         */
        s.Post_To_Account_Record_Feed__c = true;
        s.Post_To_Contact_Record_Feed__c = true;
        update s;
        
        r = chatter_notification.notify_checkin_to_record_feed(g);
        system.assertEquals(true, r);
        
        fis = [select id, linkUrl from feedItem where parentId = :a.id];
        found = false;
        for (feedItem fi : fis){
            if (fi.linkUrl == '/' + s.id){
                found = true;
                break;
            }
        }
        system.assertEquals(true, found);
        
        fis = [select id, linkUrl from feedItem where parentId = :c.id];
        found = false;
        for (feedItem fi : fis){
            if (fi.linkUrl == '/' + s.id){
                found = true;
                break;
            }
        }
        system.assertEquals(true, found);
        
        /*
        guest is set.
        contact is linked.
        contact does not exists.
         */
        delete c;
        
        r = chatter_notification.notify_checkin_to_record_feed(g);
        system.assertEquals(false, r);
    }
}